name: 'Workflow dispatch Test1_college_temp'
on: 
  workflow_dispatch:
    inputs:
      college_name:
        description: 'Your college name'
        required: true
        default: 'NIT'
        type: string
      years:
        description: 'Your college Years'
        required: true
        type: number
        default: 50
        

jobs:
  print-details:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Print name
        if: ${{ inputs.college_name }}
        run: echo ${{ inputs.college_name }}
      
      - name: Print age
        if: ${{ inputs.years }}
        run: echo ${{ inputs.years }}
  call-reusable_workflow:
    uses: .github/workflows/test_workflow_call1.yml
    with:
      username: ${{ inputs.college_name }}
  
